# Generated by Django 4.1.3 on 2023-08-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_document_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Document",
        ),
    ]
